//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanks.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tanks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap Bullet {
            get {
                object obj = ResourceManager.GetObject("Bullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Down_0 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Down_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Down_1 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Down_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Down_2 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Down_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Down_3 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Down_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Down_4 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Down_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Down_5 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Down_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Down_6 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Down_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Down_7 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Down_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Left_0 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Left_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Left_1 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Left_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Left_2 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Left_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Left_3 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Left_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Left_4 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Left_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Left_5 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Left_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Left_6 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Left_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Left_7 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Left_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Right_0 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Right_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Right_1 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Right_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Right_2 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Right_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Right_3 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Right_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Right_4 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Right_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Right_5 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Right_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Right_6 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Right_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Right_7 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Right_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Up_0 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Up_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Up_1 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Up_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Up_2 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Up_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Up_3 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Up_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Up_4 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Up_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Up_5 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Up_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Up_6 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Up_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EnemyTank_Up_7 {
            get {
                object obj = ResourceManager.GetObject("EnemyTank_Up_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Down_0 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Down_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Down_1 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Down_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Down_2 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Down_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Down_3 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Down_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Down_4 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Down_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Down_5 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Down_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Down_6 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Down_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Down_7 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Down_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Left_0 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Left_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Left_1 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Left_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Left_2 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Left_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Left_3 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Left_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Left_4 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Left_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Left_5 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Left_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Left_6 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Left_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Left_7 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Left_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Right_0 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Right_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Right_1 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Right_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Right_2 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Right_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Right_3 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Right_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Right_4 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Right_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Right_5 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Right_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Right_6 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Right_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Right_7 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Right_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Up_0 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Up_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Up_1 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Up_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Up_2 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Up_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Up_3 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Up_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Up_4 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Up_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Up_5 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Up_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Up_6 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Up_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OurTank_Up_7 {
            get {
                object obj = ResourceManager.GetObject("OurTank_Up_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Wall {
            get {
                object obj = ResourceManager.GetObject("Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
